version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vset_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: vset
    ports:
      - "5432:5432"
    volumes:
      - vset_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  vset_pg_data:
