"""Map collected evidence to a complete canonical report JSON tree.

This is a PURE FUNCTION — no I/O, no LLM calls, no side effects.
The output must pass version_gate + schema_validator + ReportImportService.

Canonical JSON contract:
    canonical.meta.canonical_version = "commercial-screen-canonical.2"
    canonical.content.final.meta.schema_version = "vset.screen.v2"
    canonical.content.sections[].blocks = [type, title, ...payload]  (tuple format)
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from app.domain.entities.discovery import (
    CompanyProfile,
    Evidence,
    EvidenceSource,
    PersonProfile,
    generate_content_fingerprint,
    generate_screen_id,
)


# ── Constants ──────────────────────────────────────────────────────────

CANONICAL_VERSION = "commercial-screen-canonical.2"
SCHEMA_VERSION = "vset.screen.v2"
NOT_ESTABLISHED = "Not established from public sources."
PRODUCT_NAME = "COMMERCIAL_SCREEN"


# ── Public API ─────────────────────────────────────────────────────────

def build_canonical_report(
    evidence: Evidence,
    company_name: str,
    founder_names: list[str],
) -> dict[str, Any]:
    """Build a complete canonical JSON tree from collected evidence.

    Returns a dict that passes ``version_gate`` + ``schema_validator`` and
    can be fed directly to ``ReportImportService.import_report()``.
    """
    now = datetime.now(timezone.utc)
    now_iso = now.isoformat()
    now_date = now.strftime("%Y-%m-%d")
    now_human = now.strftime("%-d %B %Y") if not _is_windows() else now.strftime("%d %B %Y").lstrip("0")

    screen_id = generate_screen_id(company_name)
    report_ref = screen_id.replace("cs_", "")[:12]

    cp = evidence.company_profile
    website = _resolve_website(cp, evidence)

    # ── Sections ───────────────────────────────────────────────────────
    sections = [
        _build_company_section(evidence, company_name, website, now_human),
        _build_team_section(evidence, company_name, founder_names),
        _build_product_section(evidence, company_name),
        _build_validation_section(evidence, company_name),
        _build_market_section(evidence, company_name),
        _build_competition_section(evidence, company_name),
        _build_funding_section(evidence, company_name),
    ]

    # ── Actions (SECTION_REQUEST) ──────────────────────────────────────
    actions = _build_section_actions(sections)

    # ── Action requirements (DD questions + documents) ─────────────────
    action_requirements = _build_action_requirements(company_name)

    # ── Source register ────────────────────────────────────────────────
    source_register = _build_source_register(evidence)

    # ── Report basis ───────────────────────────────────────────────────
    report_basis = {
        "about": (
            f"This report is an independent public-source assessment of {company_name}. "
            "Data was gathered automatically from publicly available web pages. "
            "No non-public or confidential information was used."
        ),
        "limitations": [
            "Some information may be behind authentication walls and could not be retrieved.",
            "This report was generated by an automated discovery process and should be reviewed by a human analyst.",
            "Financial and operational claims have not been independently verified.",
        ],
        "research_window": {
            "from": now_date,
            "to": now_date,
        },
    }

    # ── Concerns & conflicts ──────────────────────────────────────────
    concerns_conflicts = {
        "concerns": [],
        "conflicts": [],
        "message": "No material concerns or conflicts were identified during this automated screen.",
    }

    # ── Assemble content ──────────────────────────────────────────────
    content: dict[str, Any] = {
        "cover": {
            "company_name": company_name,
            "report_reference": report_ref,
            "research_cutoff": now_human,
            "website": website or "",
        },
        "sections": sections,
        "actions": actions,
        "action_requirements": action_requirements,
        "body_gate": {},
        "final": {
            "meta": {
                "schema_version": SCHEMA_VERSION,
                "as_of_date": now_date,
            },
            "evidence_register": source_register,
            "report_basis": report_basis,
            "concerns_conflicts": concerns_conflicts,
        },
    }

    # ── Fingerprint ───────────────────────────────────────────────────
    content_str = json.dumps(content, sort_keys=True, default=str)
    fingerprint = generate_content_fingerprint(content_str)

    # ── Canonical meta ────────────────────────────────────────────────
    canonical_meta: dict[str, Any] = {
        "canonical_screen_id": screen_id,
        "canonical_version": CANONICAL_VERSION,
        "company_name": company_name,
        "final_fingerprint": fingerprint,
        "canonical_content_fingerprint": fingerprint,
        "website": website,
        "report_id": f"discovery-{_slugify(company_name)}",
        "research_cutoff": now_date,
        "generated_at": now_iso,
        "version": "V1",
        "audience": "FOUNDER",
    }

    # Also write fingerprint into final.meta
    content["final"]["meta"]["final_fingerprint"] = fingerprint

    # ── Top-level meta ────────────────────────────────────────────────
    top_meta: dict[str, Any] = {
        "audience": "FOUNDER",
        "company_name": company_name,
        "website": website or "",
        "canonical_screen_id": screen_id,
        "canonical_content_fingerprint": fingerprint,
        "generated_at": now_iso,
        "research_cutoff": now_date,
        "report_id": f"discovery-{_slugify(company_name)}",
        "product": PRODUCT_NAME,
        "version": "V1",
    }

    # ── Presentation ──────────────────────────────────────────────────
    slug = _slugify(company_name)
    presentation: dict[str, Any] = {
        "audience_label": "Founder Screen",
        "action_section_title": "Investor questions & information to prepare",
        "action_intro": (
            "Part A lists the questions an investor would likely ask during a first "
            "screening call. Part B lists supporting documents and data to prepare."
        ),
        "action_part_a_title": "A. Questions to prepare for",
        "action_part_b_title": "B. Supporting documents & data to prepare",
        "about_screen_audience_text": (
            f"This report was prepared for the founding team of {company_name} "
            "to help them prepare for investor screening conversations."
        ),
        "filename_stem": f"{slug}_founder_screen",
        "pdf_title": f"{company_name} — Startup Screening Report",
        "pdf_subject": f"Startup screening report for {company_name}",
        "section_action_heading": "Information to prepare",
    }

    return {
        "canonical": {
            "meta": canonical_meta,
            "content": content,
        },
        "meta": top_meta,
        "presentation": presentation,
    }


# ── Section builders ───────────────────────────────────────────────────

def _build_company_section(
    evidence: Evidence, company_name: str, website: str | None, cutoff: str,
) -> dict[str, Any]:
    """Section 1: Key facts & context."""
    cp = evidence.company_profile
    description = _or_not_established(cp.description if cp else None)

    # Ribbon (key facts shown in the section header)
    ribbon: list[list[str]] = []
    if cp:
        if cp.headquarters:
            ribbon.append(["Base country", cp.headquarters])
        if cp.founded_year:
            ribbon.append(["Founded", cp.founded_year])
        if cp.industry:
            ribbon.append(["Sector", cp.industry])
        if cp.company_size:
            ribbon.append(["Company size", cp.company_size])

    blocks: list[list[Any]] = [
        ["para", "What the company does", description],
        ["kv", "Company profile", _company_profile_kv(cp, company_name, website)],
    ]

    # Website-sourced about text
    about_text = _extract_about_from_pages(evidence.website_pages)
    if about_text:
        blocks.append(["para", "About (from website)", about_text])

    blocks.append(["list", "Information gaps", [
        f"Research cutoff: {cutoff}",
        "This section was auto-generated from public sources.",
    ]])

    return {
        "key": "company",
        "title": "Key facts & context",
        "ribbon": ribbon,
        "blocks": blocks,
    }


def _build_team_section(
    evidence: Evidence, company_name: str, founder_names: list[str],
) -> dict[str, Any]:
    """Section 2: Founder & team."""
    founder_cards = _build_founder_cards(evidence, founder_names)

    kv_pairs: list[list[str]] = [
        ["Founding team", str(len(founder_names))],
    ]

    blocks: list[list[Any]] = [
        ["kv", None, kv_pairs],
    ]

    if founder_cards:
        blocks.append(["cards", "Founder details", founder_cards])
    else:
        blocks.append(["para", "Founder details", NOT_ESTABLISHED])

    blocks.append(["list", "Information gaps", [
        "Full employment history not publicly available for all founders.",
        "Team composition beyond founders not established.",
    ]])

    return {
        "key": "team",
        "title": "Founder & team",
        "ribbon": [],
        "blocks": blocks,
    }


def _build_product_section(evidence: Evidence, company_name: str) -> dict[str, Any]:
    """Section 3: Product & technology."""
    product_text = _extract_product_from_pages(evidence.website_pages)

    blocks: list[list[Any]] = [
        ["para", "Product overview", _or_not_established(product_text)],
        ["list", "Information gaps", [
            "Detailed product specifications not established from public sources.",
            "Intellectual property and patents not established.",
        ]],
    ]

    return {
        "key": "product",
        "title": "Product & technology",
        "ribbon": [],
        "blocks": blocks,
    }


def _build_validation_section(evidence: Evidence, company_name: str) -> dict[str, Any]:
    """Section 4: Validation & market signals."""
    blocks: list[list[Any]] = [
        ["para", "Validation status", NOT_ESTABLISHED],
        ["list", "Information gaps", [
            "Customer traction and revenue not established from public sources.",
            "Partnership and pilot details not established.",
        ]],
    ]
    return {
        "key": "validation",
        "title": "Validation & market signals",
        "ribbon": [],
        "blocks": blocks,
    }


def _build_market_section(evidence: Evidence, company_name: str) -> dict[str, Any]:
    """Section 5: Market opportunity."""
    cp = evidence.company_profile
    industry = cp.industry if cp else None

    blocks: list[list[Any]] = [
        ["para", "Market overview",
         f"{company_name} operates in the {industry} sector." if industry else NOT_ESTABLISHED],
        ["list", "Information gaps", [
            "Total addressable market size not established.",
            "Growth rates and demand drivers not established.",
        ]],
    ]
    return {
        "key": "market",
        "title": "Market opportunity",
        "ribbon": [],
        "blocks": blocks,
    }


def _build_competition_section(evidence: Evidence, company_name: str) -> dict[str, Any]:
    """Section 6: Competitive landscape."""
    blocks: list[list[Any]] = [
        ["para", "Competitive position", NOT_ESTABLISHED],
        ["list", "Information gaps", [
            "Direct competitors not identified from public sources.",
            "Competitive differentiation not established.",
        ]],
    ]
    return {
        "key": "competition",
        "title": "Competitive landscape",
        "ribbon": [],
        "blocks": blocks,
    }


def _build_funding_section(evidence: Evidence, company_name: str) -> dict[str, Any]:
    """Section 7: Funding history."""
    funding_text = _extract_funding_from_news(evidence.news_articles)

    blocks: list[list[Any]] = [
        ["para", "Funding overview", _or_not_established(funding_text)],
        ["list", "Information gaps", [
            "Full funding history not established from public sources.",
            "Cap table and investor details not established.",
        ]],
    ]
    return {
        "key": "funding",
        "title": "Funding history",
        "ribbon": [],
        "blocks": blocks,
    }


# ── Actions / DD builders ─────────────────────────────────────────────

def _build_section_actions(sections: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Generate SECTION_REQUEST action items from gap lists."""
    actions: list[dict[str, Any]] = []
    idx = 0
    for section in sections:
        for block in section.get("blocks", []):
            if isinstance(block, list) and block[0] == "list" and "Information gaps" in str(block[1]):
                for item_text in block[2] if len(block) > 2 and isinstance(block[2], list) else []:
                    actions.append({
                        "action_id": f"act_disc_{idx:04d}",
                        "kind": "SECTION_REQUEST",
                        "where": section["title"],
                        "text": item_text,
                        "why": "Not established from public sources.",
                        "key": section["key"],
                        "semantic_key": f"{section['key']}.gap.{idx}",
                    })
                    idx += 1
    return actions


def _build_action_requirements(company_name: str) -> dict[str, Any]:
    """Generate standard DD questions and documents."""
    return {
        "topics": [
            {
                "topic": "Revenue & traction",
                "items": [
                    {
                        "action_id": "act_q_001",
                        "text": f"What is {company_name}'s current monthly or annual revenue (or run-rate)?",
                        "why": "Revenue not established from public sources.",
                        "domain": "Revenue & traction",
                        "key": "revenue_current",
                        "semantic_key": "dd.revenue.current",
                    },
                    {
                        "action_id": "act_q_002",
                        "text": f"How many paying customers does {company_name} have?",
                        "why": "Customer count not established from public sources.",
                        "domain": "Revenue & traction",
                        "key": "customers_count",
                        "semantic_key": "dd.revenue.customers",
                    },
                ],
            },
            {
                "topic": "Fundraising",
                "items": [
                    {
                        "action_id": "act_q_003",
                        "text": f"What is the current fundraising target and intended use of funds?",
                        "why": "Fundraising plans not established from public sources.",
                        "domain": "Fundraising",
                        "key": "fundraising_target",
                        "semantic_key": "dd.fundraising.target",
                    },
                ],
            },
        ],
        "documents": [
            {
                "group": "Corporate, legal & ownership",
                "priority": [
                    "Certificate of incorporation and any amendments",
                    "Cap table (current, fully diluted)",
                ],
                "priority_ids": ["doc_corp_001", "doc_corp_002"],
                "secondary": [
                    "Shareholders' agreement",
                ],
                "secondary_ids": ["doc_corp_003"],
            },
            {
                "group": "Financial",
                "priority": [
                    "Latest management accounts or financial statements",
                    "Revenue breakdown by product/customer/geography",
                ],
                "priority_ids": ["doc_fin_001", "doc_fin_002"],
                "secondary": [],
                "secondary_ids": [],
            },
        ],
        "coverage": [],
        "adaptations": [],
    }


# ── Source register ────────────────────────────────────────────────────

def _build_source_register(evidence: Evidence) -> dict[str, Any]:
    """Build the evidence_register from collected sources."""
    sources_list: list[dict[str, Any]] = []
    for src in evidence.sources:
        sources_list.append({
            "source_id": src.source_id,
            "title": src.title,
            "publisher": src.publisher,
            "published_date": src.published_date,
            "display_url": _make_display_url(src.url),
            "canonical_url": src.url,
            "source_type": src.source_type,
            "ownership_class": "UNRESOLVED",
            "document_key": f"url:{src.url}",
            "original_urls": [src.url],
            "versions": [{"content_fingerprint": None, "retrieved_date": src.retrieved_at, "version_id": None}],
        })

    return {
        "sources": sources_list,
        "claims": [],
        "profile_by_domain": {},
    }


# ── Founder card helpers ───────────────────────────────────────────────

def _build_founder_cards(
    evidence: Evidence, founder_names: list[str],
) -> list[dict[str, Any]]:
    """Build founder card dicts matching the existing FounderCard shape."""
    cards: list[dict[str, Any]] = []

    # Build a lookup: lowercased name fragments → profile
    profile_map: dict[str, PersonProfile] = {}
    for p in evidence.founder_profiles:
        if p.name:
            profile_map[p.name.lower()] = p

    for name in founder_names:
        profile = _find_profile(name, profile_map)

        lines: list[list[str]] = []
        fit = ""

        if profile:
            # Education line
            edu_parts = [
                f"{e.get('degree', '')} — {e.get('institution', '')} ({e.get('year', '')})"
                for e in profile.education
                if e.get("institution")
            ]
            if edu_parts:
                lines.append(["Education", "; ".join(edu_parts)])

            # Experience line
            exp_parts = [
                f"{e.get('title', '')} at {e.get('company', '')} ({e.get('duration', '')})"
                for e in profile.experience
                if e.get("company")
            ]
            if exp_parts:
                lines.append(["Experience", "; ".join(exp_parts)])
            elif profile.headline:
                lines.append(["Current role", profile.headline])

            # Fit summary
            if profile.summary:
                fit = profile.summary[:300]
            elif profile.headline:
                fit = f"{name}'s background as {profile.headline} is relevant to {name}'s role."

            role = profile.headline or "Co-founder"
        else:
            lines.append(["Profile", "Not retrievable from public sources."])
            fit = "Founder profile could not be retrieved from public sources."
            role = "Co-founder"

        cards.append({
            "name": name,
            "role": role,
            "lines": lines,
            "fit": fit,
        })

    return cards


def _find_profile(name: str, profile_map: dict[str, PersonProfile]) -> PersonProfile | None:
    """Fuzzy match a founder name to a scraped profile."""
    name_lower = name.lower()
    # Exact match
    if name_lower in profile_map:
        return profile_map[name_lower]
    # Partial match (last name)
    parts = name_lower.split()
    for key, profile in profile_map.items():
        if any(part in key for part in parts if len(part) > 2):
            return profile
    return None


# ── Text extraction helpers ────────────────────────────────────────────

def _extract_about_from_pages(pages: list[Any]) -> str | None:
    """Extract about text from website pages."""
    for page in pages:
        if hasattr(page, "text") and page.text:
            text = page.text.strip()
            if len(text) > 50:
                return text[:1500]
    return None


def _extract_product_from_pages(pages: list[Any]) -> str | None:
    """Extract product info from website pages."""
    for page in pages:
        url = getattr(page, "url", "")
        if "product" in url.lower() or "service" in url.lower():
            text = getattr(page, "text", "").strip()
            if text:
                return text[:1500]
    return None


def _extract_funding_from_news(articles: list[Any]) -> str | None:
    """Extract funding mentions from news articles."""
    for article in articles:
        text = getattr(article, "text", "").strip()
        title = getattr(article, "title", "").strip()
        combined = f"{title} {text}".lower()
        if any(kw in combined for kw in ["funding", "raised", "investment", "seed", "series"]):
            return text[:1500] if text else title
    return None


# ── Utility helpers ────────────────────────────────────────────────────

def _company_profile_kv(
    cp: CompanyProfile | None, company_name: str, website: str | None,
) -> list[list[str]]:
    """Build KV pairs for the company profile block."""
    pairs: list[list[str]] = [
        ["Legal name", company_name],
    ]
    if cp:
        if cp.industry:
            pairs.append(["Sector", cp.industry])
        if cp.headquarters:
            pairs.append(["Headquarters", cp.headquarters])
        if cp.company_size:
            pairs.append(["Company size", cp.company_size])
        if cp.founded_year:
            pairs.append(["Founded", cp.founded_year])
        if cp.specialties:
            pairs.append(["Specialties", ", ".join(cp.specialties)])
    if website:
        pairs.append(["Website", website])

    return pairs


def _resolve_website(cp: CompanyProfile | None, evidence: Evidence) -> str | None:
    """Get the best website URL from evidence."""
    if cp and cp.website:
        return cp.website
    if evidence.website_pages:
        return evidence.website_pages[0].url
    return None


def _make_display_url(url: str) -> str:
    """Convert a full URL to a display URL (strip scheme)."""
    return url.replace("https://", "").replace("http://", "").rstrip("/")


def _or_not_established(value: str | None) -> str:
    """Return value or NOT_ESTABLISHED sentinel."""
    if value and value.strip():
        return value.strip()
    return NOT_ESTABLISHED


def _slugify(name: str) -> str:
    """Simple slugify for identifiers."""
    import re
    cleaned = re.sub(r"[^a-zA-Z0-9\s-]", "", name).strip().lower()
    return re.sub(r"[\s-]+", "-", cleaned)


def _is_windows() -> bool:
    """Check if running on Windows (affects strftime)."""
    import sys
    return sys.platform == "win32"
