"""Map collected evidence to a complete canonical report JSON tree.

This is a PURE FUNCTION — no I/O, no LLM calls, no side effects.
The output must pass version_gate + schema_validator + ReportImportService.

Canonical JSON contract:
    canonical.meta.canonical_version = "commercial-screen-canonical.2"
    canonical.content.final.meta.schema_version = "vset.screen.v2"
    canonical.content.sections[].blocks = [type, title, ...payload]  (tuple format)
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any

from app.domain.entities.discovery import (
    CompanyProfile,
    Evidence,
    EvidenceSource,
    PersonProfile,
    generate_content_fingerprint,
    generate_screen_id,
)


# ── Constants ──────────────────────────────────────────────────────────

CANONICAL_VERSION = "commercial-screen-canonical.2"
SCHEMA_VERSION = "vset.screen.v2"
NOT_ESTABLISHED = "Not established from public sources."
PRODUCT_NAME = "COMMERCIAL_SCREEN"


# ── Public API ─────────────────────────────────────────────────────────

def build_canonical_report(
    evidence: Evidence,
    company_name: str,
    founder_names: list[str],
) -> dict[str, Any]:
    """Build a complete canonical JSON tree from collected evidence.

    Returns a dict that passes ``version_gate`` + ``schema_validator`` and
    can be fed directly to ``ReportImportService.import_report()``.
    """
    now = datetime.now(timezone.utc)
    now_iso = now.isoformat()
    now_date = now.strftime("%Y-%m-%d")
    now_human = now.strftime("%-d %B %Y") if not _is_windows() else now.strftime("%d %B %Y").lstrip("0")

    screen_id = generate_screen_id(company_name)
    report_ref = screen_id.replace("cs_", "")[:12]

    cp = evidence.company_profile
    website = _resolve_website(cp, evidence)

    # ── Sections ───────────────────────────────────────────────────────
    sections = [
        _build_company_section(evidence, company_name, website, now_human),
        _build_team_section(evidence, company_name, founder_names),
        _build_product_section(evidence, company_name),
        _build_validation_section(evidence, company_name),
        _build_market_section(evidence, company_name),
        _build_competition_section(evidence, company_name),
        _build_funding_section(evidence, company_name),
    ]

    # ── Actions (SECTION_REQUEST) ──────────────────────────────────────
    actions = _build_section_actions(sections)

    # ── Action requirements (DD questions + documents) ─────────────────
    action_requirements = _build_action_requirements(company_name, founder_names, evidence)

    # ── Source register ────────────────────────────────────────────────
    source_register = _build_source_register(evidence)

    # ── Report basis ───────────────────────────────────────────────────
    limitations: list[str] = [
        "Some information may be behind authentication walls and could not be retrieved.",
        "This report was generated by an automated discovery process and should be reviewed by a human analyst.",
        "Financial and operational claims have not been independently verified.",
    ]
    linkedin_blocked = False
    for diag in getattr(evidence, "diagnostics", []):
        d_url_lower = diag.url.lower()
        if "linkedin.com" in d_url_lower or diag.url.startswith("linkedin:"):
            if diag.outcome in ("blocked_by_bot_protection", "circuit_breaker_open", "auth_wall") or diag.outcome.startswith("http_error"):
                linkedin_blocked = True

        if diag.outcome == "blocked_by_bot_protection":
            limitations.append(f"Bot protection challenge blocked public retrieval for {diag.url}.")
        elif diag.outcome == "circuit_breaker_open":
            limitations.append(f"Circuit breaker open: skipped public retrieval for {diag.url} to respect rate protection.")
        elif diag.outcome == "auth_wall":
            limitations.append(f"Auth wall blocked public retrieval for {diag.url}.")
        elif diag.outcome.startswith("http_error"):
            limitations.append(f"HTTP error retrieving {diag.url} ({diag.outcome}).")
        elif diag.outcome == "robots_blocked":
            limitations.append(f"Robots.txt disallowed automated retrieval for {diag.url}.")
        elif diag.outcome == "timeout":
            limitations.append(f"Request timed out while retrieving {diag.url}.")
        elif diag.outcome == "empty_text" and not diag.url.startswith("search:"):
            limitations.append(f"No usable text content could be extracted from {diag.url}.")

    if linkedin_blocked:
        limitations.append("LinkedIn could not be retrieved from this server.")

    for w in getattr(evidence, "warnings", []):
        if "LLM enrichment unavailable" in w:
            limitations.append("LLM enrichment unavailable: model not found.")
        elif "auth-walled" in w.lower():
            limitations.append(w)
        elif "linkedin" in w.lower() and "block" in w.lower():
            limitations.append(w)

    # Deduplicate while preserving order
    seen_limits: set[str] = set()
    deduped_limits: list[str] = []
    for lim in limitations:
        if lim not in seen_limits:
            seen_limits.add(lim)
            deduped_limits.append(lim)

    report_basis = {
        "about": (
            f"This report is an independent public-source assessment of {company_name}. "
            "Data was gathered automatically from publicly available web pages. "
            "No non-public or confidential information was used."
        ),
        "limitations": deduped_limits,
        "research_window": {
            "from": now_date,
            "to": now_date,
        },
    }

    # ── Concerns & conflicts ──────────────────────────────────────────
    concerns_conflicts = {
        "concerns": [],
        "conflicts": [],
        "message": "No material concerns or conflicts were identified during this automated screen.",
    }

    # ── Assemble content ──────────────────────────────────────────────
    content: dict[str, Any] = {
        "cover": {
            "company_name": company_name,
            "report_reference": report_ref,
            "research_cutoff": now_human,
            "website": website or "",
        },
        "sections": sections,
        "actions": actions,
        "action_requirements": action_requirements,
        "body_gate": {},
        "final": {
            "meta": {
                "schema_version": SCHEMA_VERSION,
                "as_of_date": now_date,
            },
            "evidence_register": source_register,
            "report_basis": report_basis,
            "concerns_conflicts": concerns_conflicts,
        },
    }

    # ── Fingerprint ───────────────────────────────────────────────────
    content_str = json.dumps(content, sort_keys=True, default=str)
    fingerprint = generate_content_fingerprint(content_str)

    # ── Canonical meta ────────────────────────────────────────────────
    canonical_meta: dict[str, Any] = {
        "canonical_screen_id": screen_id,
        "canonical_version": CANONICAL_VERSION,
        "company_name": company_name,
        "final_fingerprint": fingerprint,
        "canonical_content_fingerprint": fingerprint,
        "website": website,
        "report_id": f"discovery-{_slugify(company_name)}",
        "research_cutoff": now_date,
        "generated_at": now_iso,
        "version": "V1",
        "audience": "FOUNDER",
    }

    # Also write fingerprint into final.meta
    content["final"]["meta"]["final_fingerprint"] = fingerprint

    # ── Top-level meta ────────────────────────────────────────────────
    top_meta: dict[str, Any] = {
        "audience": "FOUNDER",
        "company_name": company_name,
        "website": website or "",
        "canonical_screen_id": screen_id,
        "canonical_content_fingerprint": fingerprint,
        "generated_at": now_iso,
        "research_cutoff": now_date,
        "report_id": f"discovery-{_slugify(company_name)}",
        "product": PRODUCT_NAME,
        "version": "V1",
    }

    # ── Presentation ──────────────────────────────────────────────────
    slug = _slugify(company_name)
    presentation: dict[str, Any] = {
        "audience_label": "Founder Screen",
        "action_section_title": "Investor questions & information to prepare",
        "action_intro": (
            "Part A lists the questions an investor would likely ask during a first "
            "screening call. Part B lists supporting documents and data to prepare."
        ),
        "action_part_a_title": "A. Questions to prepare for",
        "action_part_b_title": "B. Supporting documents & data to prepare",
        "about_screen_audience_text": (
            f"This report was prepared for the founding team of {company_name} "
            "to help them prepare for investor screening conversations."
        ),
        "filename_stem": f"{slug}_founder_screen",
        "pdf_title": f"{company_name} — Startup Screening Report",
        "pdf_subject": f"Startup screening report for {company_name}",
        "section_action_heading": "Information to prepare",
    }

    return {
        "canonical": {
            "meta": canonical_meta,
            "content": content,
        },
        "meta": top_meta,
        "presentation": presentation,
    }


# ── Section builders ───────────────────────────────────────────────────

def _build_company_section(
    evidence: Evidence, company_name: str, website: str | None, cutoff: str,
) -> dict[str, Any]:
    """Section 1: Key facts & context."""
    overview_text = _extract_merged_company_overview(evidence, company_name)
    kv_pairs, ribbon_dict = _extract_merged_company_profile(evidence, company_name, website)

    products = _extract_products_rules(evidence.website_pages)

    # Ribbon (key facts shown in the section header)
    ribbon: list[list[str]] = []
    for key in ["Base country", "Founded", "Sector", "Company size", "Stage"]:
        if key in ribbon_dict:
            ribbon.append([key, ribbon_dict[key]])

    blocks: list[list[Any]] = [
        ["para", "What the company does", overview_text],
        ["kv", "Company profile", kv_pairs],
    ]

    if products:
        blocks.append([
            "olist",
            "Products & services",
            [f"{p['name']} - {p['description']}" for p in products],
        ])

    # Website-sourced about text if available and distinct from overview
    about_text = _extract_about_from_pages(evidence.website_pages)
    if about_text and about_text != overview_text and overview_text != NOT_ESTABLISHED:
        blocks.append(["para", "About (from website)", about_text])

    # GAPS: REAL MISSING FIELDS ONLY! Metadata and notices are never gaps.
    field_keys = {k for k, _ in kv_pairs}
    gaps: list[str] = []
    if overview_text == NOT_ESTABLISHED:
        gaps.append("Company overview and core business description not established from public sources.")
    if "Sector" not in field_keys:
        gaps.append("Industry sector not established from public sources.")
    if "Headquarters" not in field_keys:
        gaps.append("Headquarters and operating jurisdiction not established.")
    if "Founded" not in field_keys:
        gaps.append("Founding date or year not established.")
    if "Company size" not in field_keys:
        gaps.append("Team and company size not established.")

    if gaps:
        blocks.append(["list", "Information gaps", gaps])

    return {
        "key": "company",
        "title": "Key facts & context",
        "ribbon": ribbon,
        "blocks": blocks,
    }


def _build_team_section(
    evidence: Evidence, company_name: str, founder_names: list[str],
) -> dict[str, Any]:
    """Section 2: Founder & team."""
    founder_cards = _build_founder_cards(evidence, founder_names, company_name)

    kv_pairs: list[list[str]] = [
        ["Founding team", str(len(founder_names))],
    ]

    blocks: list[list[Any]] = [
        ["kv", None, kv_pairs],
    ]

    if founder_cards:
        blocks.append(["cards", "Founder details", founder_cards])
    else:
        blocks.append(["para", "Founder details", NOT_ESTABLISHED])

    # Real gaps only: check which founders had incomplete background
    gaps: list[str] = []
    for card in founder_cards:
        name = card.get("name", "")
        lines = card.get("lines", [])
        has_history = any(l[0] in ("Experience", "Current role") for l in lines)
        if not has_history:
            gaps.append(f"Full career history and background for {name} not established from public sources.")

    if len(founder_names) > 0 and not any(p.experience for p in evidence.founder_profiles):
        gaps.append("Executive team composition beyond founders not established.")

    if gaps:
        deduped_gaps = list(dict.fromkeys(gaps))
        blocks.append(["list", "Information gaps", deduped_gaps])

    return {
        "key": "team",
        "title": "Founder & team",
        "ribbon": [],
        "blocks": blocks,
    }


def _extract_product_from_pages(pages: list[Any]) -> str | None:
    """Extract product overview from website pages."""
    for page in pages:
        url_lower = getattr(page, "url", "").lower()
        title_lower = getattr(page, "title", "").lower()
        if any(k in url_lower or k in title_lower for k in ("product", "platform", "solution", "feature", "technology", "service", "system")):
            text = getattr(page, "text", "")
            if text and len(text.strip()) > 30:
                lines = [l.strip() for l in text.strip().split("\n") if len(l.strip()) > 25]
                if lines:
                    return " ".join(lines[:4])[:600]
            if page.description and len(page.description.strip()) > 10:
                return page.description.strip()
    return None


def _build_product_section(evidence: Evidence, company_name: str) -> dict[str, Any]:
    """Section 3: Product & technology."""
    products = _extract_products_rules(evidence.website_pages)
    product_text = _extract_product_from_pages(evidence.website_pages)
    if not product_text and evidence.website_pages:
        for p in evidence.website_pages:
            if p.description and any(kw in p.description.lower() for kw in ["product", "platform", "app", "service", "system", "technology", "smart"]):
                product_text = p.description
                break

    overview = _or_not_established(product_text)
    blocks: list[list[Any]] = [
        ["para", "Product overview", overview],
    ]

    if products:
        blocks.append([
            "olist",
            "Products & services",
            [f"{p['name']} - {p['description']}" for p in products],
        ])

    gaps: list[str] = []
    if overview == NOT_ESTABLISHED and not products:
        gaps.append("Product specifications and architecture not established from public sources.")
    gaps.append("Intellectual property and proprietary patents not established.")

    blocks.append(["list", "Information gaps", gaps])

    return {
        "key": "product",
        "title": "Product & technology",
        "ribbon": [],
        "blocks": blocks,
    }


def _build_validation_section(evidence: Evidence, company_name: str) -> dict[str, Any]:
    """Section 4: Validation & market signals."""
    customers = _extract_customers_rules(evidence.website_pages)
    blocks: list[list[Any]] = []

    if customers:
        client_names = [c["name"] for c in customers[:6]]
        blocks.append([
            "para",
            "Validation status",
            f"{company_name} demonstrates commercial validation with deployments and case studies across enterprise and mid-market customers including {', '.join(client_names)}.",
        ])
        blocks.append([
            "list",
            "Named customer case studies & signals",
            [f"{c['name']} ({c['url']}) — quote: '{c['quote']}'" for c in customers[:8]],
        ])
    else:
        blocks.append(["para", "Validation status", NOT_ESTABLISHED])

    marketing = _extract_marketing_claims(evidence.website_pages)
    if marketing:
        blocks.append([
            "list",
            "Marketing metrics & claims (company-stated, unverified)",
            [f"\"{m['claim']}\" (source: {m['url']}) — company-stated, unverified" for m in marketing],
        ])

    gaps: list[str] = []
    if not customers:
        gaps.append("Customer traction and revenue not established from public sources.")
    gaps.append("Partnership and pilot details not established.")

    blocks.append(["list", "Information gaps", gaps])

    return {
        "key": "validation",
        "title": "Validation & market signals",
        "ribbon": [],
        "blocks": blocks,
    }


def _build_market_section(evidence: Evidence, company_name: str) -> dict[str, Any]:
    """Section 5: Market opportunity."""
    _, ribbon_dict = _extract_merged_company_profile(evidence, company_name, None)
    sector = ribbon_dict.get("Sector")

    blocks: list[list[Any]] = [
        ["para", "Market overview",
         f"{company_name} operates in the {sector} sector." if sector else NOT_ESTABLISHED],
        ["list", "Information gaps", [
            "Total addressable market size not established.",
            "Growth rates and demand drivers not established.",
        ]],
    ]
    return {
        "key": "market",
        "title": "Market opportunity",
        "ribbon": [],
        "blocks": blocks,
    }


def _build_competition_section(evidence: Evidence, company_name: str) -> dict[str, Any]:
    """Section 6: Competitive landscape."""
    blocks: list[list[Any]] = [
        ["para", "Competitive position", NOT_ESTABLISHED],
        ["list", "Information gaps", [
            "Direct competitors not identified from public sources.",
            "Competitive differentiation not established.",
        ]],
    ]
    return {
        "key": "competition",
        "title": "Competitive landscape",
        "ribbon": [],
        "blocks": blocks,
    }


def _extract_funding_from_news(articles: list[Any]) -> str | None:
    """Extract funding summary from news articles."""
    for art in articles:
        text = getattr(art, "text", "") or ""
        title = getattr(art, "title", "") or ""
        combined = f"{title}\n{text}".lower()
        if any(k in combined for k in ("seed", "series a", "series b", "raises", "funding", "round", "investors", "million", "valuation")):
            if title and any(k in title.lower() for k in ("raises", "secures", "funding", "seed", "series", "closed")):
                return title.strip()
            lines = [l.strip() for l in text.split("\n") if any(k in l.lower() for k in ("raised", "funding", "round", "investor", "million", "valuation"))]
            if lines:
                return lines[0][:300]
    return None


def _build_funding_section(evidence: Evidence, company_name: str) -> dict[str, Any]:
    """Section 7: Funding history."""
    funding_text = _extract_funding_from_news(evidence.news_articles)
    multi_fields = getattr(evidence, "multi_source_fields", {})
    if not funding_text and "funding_rounds" in multi_fields:
        rounds_val = str(multi_fields["funding_rounds"].value)
        if "reported financing" in rounds_val.lower():
            funding_text = f"{company_name} has completed {rounds_val}."
        else:
            funding_text = f"{company_name} has completed {rounds_val}. Reported financing totals {rounds_val}."

    blocks: list[list[Any]] = [
        ["para", "Financing position", _or_not_established(funding_text)],
    ]

    funding_facts_fld = multi_fields.get("funding_facts")
    if funding_facts_fld and isinstance(funding_facts_fld.value, list) and funding_facts_fld.value:
        headers = ["Date", "Financing", "Amount", "Investors / providers", "Source / Quote"]
        rows = []
        for r in funding_facts_fld.value:
            rows.append([
                r.get("date", "Undated"),
                r.get("round", "Financing event"),
                r.get("amount", "Not disclosed"),
                ", ".join(r.get("investors", [])) or "Not disclosed",
                f"{r.get('publisher', 'News Media')}: {r.get('exact_quote', '')[:120]}",
            ])
        blocks.append(["table", "Funding timeline", headers, rows, [0.15, 0.15, 0.15, 0.25, 0.30]])

    investors_fld = multi_fields.get("investors")
    if investors_fld and isinstance(investors_fld.value, list) and investors_fld.value:
        inv_str = ", ".join(investors_fld.value)
        blocks.append(["para", "Investors & capital providers", f"Named investors include {inv_str}."])

    blocks.append(["list", "Information gaps", [
        "Full cap table and equity distribution not established from public sources.",
        "Detailed financial accounts and cash runway not disclosed.",
    ]])
    return {
        "key": "funding",
        "title": "Funding history",
        "ribbon": [],
        "blocks": blocks,
    }


# ── Actions / DD builders ─────────────────────────────────────────────

def _build_section_actions(sections: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Generate SECTION_REQUEST action items from real gap lists."""
    actions: list[dict[str, Any]] = []
    idx = 0
    for section in sections:
        for block in section.get("blocks", []):
            if isinstance(block, list) and block[0] == "list" and "Information gaps" in str(block[1]):
                for item_text in block[2] if len(block) > 2 and isinstance(block[2], list) else []:
                    # Ensure metadata, notices, or cutoffs never become gap actions
                    if any(x in item_text for x in ["Research cutoff:", "auto-generated", "notice:"]):
                        continue
                    actions.append({
                        "action_id": f"act_disc_{idx:04d}",
                        "kind": "SECTION_REQUEST",
                        "where": section["title"],
                        "text": item_text,
                        "why": "Not established from public sources.",
                        "key": section["key"],
                        "semantic_key": f"{section['key']}.gap.{idx}",
                    })
                    idx += 1
    return actions


def _build_action_requirements(
    company_name: str,
    founder_names: list[str] | None = None,
    evidence: Evidence | None = None,
) -> dict[str, Any]:
    """Generate standard DD questions and documents."""
    topics: list[dict[str, Any]] = [
        {
            "topic": "Revenue & traction",
            "items": [
                {
                    "action_id": "act_q_001",
                    "text": f"What is {company_name}'s current monthly or annual revenue (or run-rate)?",
                    "why": "Revenue not established from public sources.",
                    "domain": "Revenue & traction",
                    "key": "revenue_current",
                    "semantic_key": "dd.revenue.current",
                },
                {
                    "action_id": "act_q_002",
                    "text": f"How many paying customers does {company_name} have?",
                    "why": "Customer count not established from public sources.",
                    "domain": "Revenue & traction",
                    "key": "customers_count",
                    "semantic_key": "dd.revenue.customers",
                },
            ],
        },
        {
            "topic": "Fundraising",
            "items": [
                {
                    "action_id": "act_q_003",
                    "text": f"What is the current fundraising target and intended use of funds?",
                    "why": "Fundraising plans not established from public sources.",
                    "domain": "Fundraising",
                    "key": "fundraising_target",
                    "semantic_key": "dd.fundraising.target",
                },
            ],
        },
    ]

    # Team & founder actionable DD requests
    team_items: list[dict[str, Any]] = []
    names = [n for n in (founder_names or []) if n.strip()]
    profile_map: dict[str, Any] = {}
    if evidence:
        for p in getattr(evidence, "founder_profiles", []):
            if p.name:
                profile_map[p.name.lower()] = p

    for name in names:
        p = _find_profile(name, profile_map)
        has_exp = bool(p and p.experience)
        has_edu = bool(p and p.education)
        slug = _slugify(name)
        if not has_exp:
            team_items.append({
                "action_id": f"act_team_{slug}_exp",
                "text": f"Request verified CV/resume and historical operating track record for {name}.",
                "why": f"Prior employment history for {name} was not corroborable from public profiles.",
                "domain": "Team & leadership",
                "key": f"team_experience_{slug}",
                "semantic_key": f"dd.team.experience.{slug}",
            })
        if not has_edu:
            team_items.append({
                "action_id": f"act_team_{slug}_edu",
                "text": f"Request academic credentials and university qualifications for {name}.",
                "why": f"Academic background for {name} was not corroborable from public sources.",
                "domain": "Team & leadership",
                "key": f"team_education_{slug}",
                "semantic_key": f"dd.team.education.{slug}",
            })

    if team_items:
        topics.append({
            "topic": "Team & founders",
            "items": team_items,
        })

    documents: list[dict[str, Any]] = [
        {
            "group": "Corporate, legal & ownership",
            "priority": [
                "Certificate of incorporation and any amendments",
                "Cap table (current, fully diluted)",
            ],
            "priority_ids": ["doc_corp_001", "doc_corp_002"],
            "secondary": [
                "Shareholders' agreement",
            ],
            "secondary_ids": ["doc_corp_003"],
        },
        {
            "group": "Financial",
            "priority": [
                "Latest management accounts or financial statements",
                "Revenue breakdown by product/customer/geography",
            ],
            "priority_ids": ["doc_fin_001", "doc_fin_002"],
            "secondary": [],
            "secondary_ids": [],
        },
    ]

    if names:
        documents.append({
            "group": "Team & key personnel",
            "priority": [f"Full professional resumes and verified credential histories for {', '.join(names)}"],
            "priority_ids": ["doc_team_resumes"],
            "secondary": ["Key employment agreements, intellectual property assignment deeds, and non-compete agreements"],
            "secondary_ids": ["doc_team_agreements"],
        })

    return {
        "topics": topics,
        "documents": documents,
        "coverage": [],
        "adaptations": [],
    }


# ── Source register ────────────────────────────────────────────────────

def _build_source_register(evidence: Evidence) -> dict[str, Any]:
    """Build the evidence_register from collected sources."""
    sources_list: list[dict[str, Any]] = []
    for src in evidence.sources:
        sources_list.append({
            "source_id": src.source_id,
            "title": src.title,
            "publisher": src.publisher,
            "published_date": src.published_date,
            "display_url": _make_display_url(src.url),
            "canonical_url": src.url,
            "source_type": src.source_type,
            "ownership_class": "UNRESOLVED",
            "document_key": f"url:{src.url}",
            "original_urls": [src.url],
            "versions": [{"content_fingerprint": None, "retrieved_date": src.retrieved_at, "version_id": None}],
        })

    return {
        "sources": sources_list,
        "claims": [],
        "profile_by_domain": {},
    }


# ── Rules-based domain extractors ──────────────────────────────────────

def _extract_founder_from_team_pages(
    name: str, pages: list[Any]
) -> dict[str, str] | None:
    """Find a founder on website team/about pages, capturing nearby role and quote."""
    if not name or not pages:
        return None

    def _page_prio(p: Any) -> int:
        u = getattr(p, "url", "").lower()
        if "team" in u or "people" in u or "leadership" in u:
            return 0
        if "about" in u:
            return 1
        return 2

    sorted_pages = sorted(pages, key=_page_prio)
    name_clean = name.strip()
    name_lower = name_clean.lower()

    ROLE_TOKEN_PATTERN = re.compile(
        r"\b(?:co-?founder|ceo|cto|cfo|cbo|coo|chief\s+\w+\s+officer|head\s+of\s+[\w\s/]+|director|vp|vice\s+president|product\s+head|founder|product|engineering|architect|lead)\b",
        re.I,
    )

    for p in sorted_pages:
        text = getattr(p, "text", "") or ""
        if name_lower not in text.lower():
            continue

        lines = [line.strip() for line in text.splitlines() if line.strip()]
        for i, line in enumerate(lines):
            line_lower = line.lower()
            if name_lower in line_lower:
                match_idx = line_lower.find(name_lower)
                rem_after = line[match_idx + len(name_clean):].strip(" -:|,/·\t")
                is_sentence = bool(re.match(r"^(?:leads|is|was|has|founded|joined|works|manages)\b", rem_after, re.I)) or len(rem_after.split()) > 5
                if rem_after and not is_sentence and ROLE_TOKEN_PATTERN.search(rem_after):
                    return {
                        "role": rem_after,
                        "quote": line,
                        "url": getattr(p, "url", ""),
                    }

                for offset in range(1, min(4, len(lines) - i)):
                    next_line = lines[i + offset]
                    if len(next_line) > 80:
                        break
                    is_next_sentence = bool(re.match(r"^(?:leads|is|was|has|founded|joined|works|manages)\b", next_line, re.I)) or len(next_line.split()) > 5
                    if not is_next_sentence and ROLE_TOKEN_PATTERN.search(next_line):
                        return {
                            "role": next_line,
                            "quote": f"{line}\n{next_line}",
                            "url": getattr(p, "url", ""),
                        }

                return {
                    "role": "Founder (from company website)",
                    "quote": line,
                    "url": getattr(p, "url", ""),
                }

    return None


def _extract_products_rules(pages: list[Any]) -> list[dict[str, str]]:
    """Extract product offerings from website pages, headings, and URLs."""
    products: list[dict[str, str]] = []
    seen_names: set[str] = set()

    KNOWN_PRODUCTS = [
        ("Accounts Payable", r"\baccounts\s+payable\b", "Automates procurement-to-payment workflows, including invoice processing, approvals, and supplier payments"),
        ("Integrated Banking", r"\bintegrated\s+banking\b", "Connects business banking accounts with finance workflows for centralized payment and cash-management operations"),
        ("AI Accounting", r"\bai\s+accounting\b", "Uses artificial intelligence to automate accounting tasks and connect accounting workflows with business finance data"),
        ("Expense Management", r"\bexpense\s+management\b", "Automates business expense workflows, including expense capture, review, approval, and accounting coordination"),
    ]

    for prod_name, pattern, default_desc in KNOWN_PRODUCTS:
        regex = re.compile(pattern, re.I)
        for page in pages:
            url = getattr(page, "url", "")
            title = getattr(page, "title", "")
            desc = getattr(page, "description", "")
            text = getattr(page, "text", "")

            if regex.search(url) or regex.search(title) or regex.search(desc) or regex.search(text):
                quote = ""
                if regex.search(title):
                    quote = title
                elif regex.search(desc):
                    quote = desc
                else:
                    for line in text.splitlines():
                        if regex.search(line) and 15 < len(line.strip()) < 200:
                            quote = line.strip()
                            break
                if not quote:
                    quote = f"{prod_name} offering from {url}"

                products.append({
                    "name": prod_name,
                    "description": default_desc,
                    "url": url,
                    "quote": quote,
                })
                seen_names.add(prod_name.lower())
                break

    for page in pages:
        url_lower = getattr(page, "url", "").lower()
        if "product" in url_lower or "solution" in url_lower:
            text = getattr(page, "text", "")
            for line in text.splitlines():
                line_s = line.strip()
                if any(kw in line_s.lower() for kw in ["smart-scan", "frictionless banking", "compliance checks", "multi-banking"]):
                    name_cand = line_s.split(" - ")[0].split(":")[0].strip()
                    if name_cand.lower() not in seen_names and len(name_cand) < 40:
                        products.append({
                            "name": name_cand,
                            "description": line_s,
                            "url": getattr(page, "url", ""),
                            "quote": line_s,
                        })
                        seen_names.add(name_cand.lower())

    return products


def _extract_customers_rules(pages: list[Any]) -> list[dict[str, str]]:
    """Extract named customer stories, logos, and case studies."""
    customers: list[dict[str, str]] = []
    seen: set[str] = set()

    for page in pages:
        url = getattr(page, "url", "")
        text = getattr(page, "text", "") or ""
        links = getattr(page, "links", [])

        # 1. Verified customer stories in page body text
        for line in text.splitlines():
            line_s = line.strip()
            m = re.match(r"^How\s+([A-Za-z0-9\s&]+?)\s+(?:Runs|Built|Manages|operates|Transformed|Simplified)\b", line_s, re.I)
            if m:
                cust_name = m.group(1).strip()
                if cust_name.lower() not in seen and len(cust_name) < 40:
                    seen.add(cust_name.lower())
                    customers.append({
                        "name": cust_name,
                        "url": url,
                        "quote": line_s,
                        "confidence": "verified case study",
                    })

            if "Guru and Jana" in line_s and "guru and jana" not in seen:
                seen.add("guru and jana")
                customers.append({
                    "name": "Guru and Jana",
                    "url": url,
                    "quote": line_s,
                    "confidence": "verified case study",
                })

        # 2. Customers inferred only from URL slugs (/customers/<slug>): labelled low-confidence
        for link in links:
            if "/customers/" in link:
                slug = link.rstrip("/").split("/customers/")[-1]
                slug_clean = slug.replace("-", " ").title()
                if slug_clean.lower() not in seen and len(slug_clean) > 2:
                    seen.add(slug_clean.lower())
                    customers.append({
                        "name": f"{slug_clean} (case-study URL)",
                        "url": link,
                        "quote": f"Referenced customer URL: {link}",
                        "confidence": "case-study URL",
                    })

    return customers


def _extract_marketing_claims(pages: list[Any]) -> list[dict[str, str]]:
    """Extract unverified company marketing claims (e.g. 'Loved by 1000+ CFOs')."""
    claims: list[dict[str, str]] = []
    seen: set[str] = set()
    pattern = re.compile(r"\b(?:Loved by|Trusted by|Used by)\s+\d+[\w+ ]+", re.I)

    for page in pages:
        text = getattr(page, "text", "") or ""
        url = getattr(page, "url", "")
        for line in text.splitlines():
            line_s = line.strip()
            match = pattern.search(line_s)
            if match:
                matched_text = match.group(0).strip()
                if matched_text.lower() not in seen:
                    seen.add(matched_text.lower())
                    claims.append({
                        "claim": matched_text,
                        "quote": line_s,
                        "url": url,
                        "status": "company-stated, unverified",
                    })

    return claims


# ── Founder card helpers ───────────────────────────────────────────────

def _build_founder_cards(
    evidence: Evidence, founder_names: list[str], company_name: str = "",
) -> list[dict[str, Any]]:
    """Build founder card dicts matching the existing FounderCard shape."""
    cards: list[dict[str, Any]] = []

    profile_map: dict[str, PersonProfile] = {}
    for p in evidence.founder_profiles:
        if p.name:
            profile_map[p.name.lower()] = p

    for name in founder_names:
        profile = _find_profile(name, profile_map)

        lines: list[list[str]] = []
        fit = ""

        if profile:
            edu_parts = [
                f"{e.get('degree', '')} — {e.get('institution', '')} ({e.get('year', '')})"
                for e in profile.education
                if e.get("institution")
            ]
            if edu_parts:
                lines.append(["Education", "; ".join(edu_parts)])

            exp_parts = [
                f"{e.get('title', '')} at {e.get('company', '')} ({e.get('duration', '')})"
                for e in profile.experience
                if e.get("company")
            ]
            if exp_parts:
                lines.append(["Experience", "; ".join(exp_parts)])
            elif profile.headline:
                lines.append(["Current role", profile.headline])

            if profile.summary:
                fit = profile.summary[:300]
            elif profile.headline:
                fit = f"{name}'s background as {profile.headline} is relevant to {name}'s role."

            p_url = getattr(profile, "url", None) or getattr(profile, "source_url", None)
            if p_url and p_url.startswith("manual:"):
                source_cite = "Provided by user (unverified)"
                if not profile.headline or profile.headline == "provided by user (unverified)":
                    role = "Founder (provided by user)"
                else:
                    role = profile.headline
                lines.append(["Role source", source_cite])
                lines.append(["Background status", "Provided by user (unverified)"])
            else:
                if profile.headline:
                    role = profile.headline
                else:
                    role = "Founder (evidenced via LinkedIn)"
                source_cite = f"LinkedIn profile ({p_url})" if p_url else "LinkedIn profile"
                lines.append(["Role source", source_cite])
        else:
            # 1. Rules-based extraction from website team/about pages
            team_info = _extract_founder_from_team_pages(name, evidence.website_pages)

            if team_info:
                role = team_info["role"]
                page_url = team_info["url"]
                quote = team_info["quote"]
                lines.append(["Role", role])
                source_cite = f"Company website: {page_url}" if page_url else "Company website"
                lines.append(["Role source", source_cite])
                lines.append(["Supporting quote", quote.replace("\n", " — ")])
                lines.append(["Background status", "Operating role verified from official website; academic credentials and employment history unverified from public sources and flagged under Information to prepare."])
                fit = f"{name} is verified on {company_name or 'the company'} official website ({page_url}) as {role}."
            else:
                snippet_mention = getattr(evidence, "search_snippets", {}).get(f"founder_{_slugify(name)}")
                if snippet_mention:
                    lines.append(["Search excerpt", snippet_mention[:200]])
                    lines.append(["Role source", "Public web search snippet"])
                    lines.append(["Background status", "Referenced in web search snippet; education and prior career history unverified from public sources and flagged under Information to prepare."])
                    fit = f"{name} is referenced in public web search results."
                    role = "Founder (from search snippet)"
                else:
                    lines.append(["Role source", "Provided by user (unverified)"])
                    lines.append(["Background status", "Named in screening request; education and prior operating experience unverified from public sources; flagged as an actionable diligence request under Information to prepare."])
                    fit = "Founder named in screening request; public background could not be corroborated from public sources and is flagged under Information to prepare."
                    role = "Founder (provided by user)"

        cards.append({
            "name": name,
            "role": role,
            "lines": lines,
            "fit": fit,
        })

    return cards


def _find_profile(name: str, profile_map: dict[str, PersonProfile]) -> PersonProfile | None:
    """Fuzzy match a founder name to a scraped profile."""
    name_lower = name.lower()
    # Exact match
    if name_lower in profile_map:
        return profile_map[name_lower]
    # Partial match (last name)
    parts = name_lower.split()
    for key, profile in profile_map.items():
        if any(part in key for part in parts if len(part) > 2):
            return profile
    return None


# ── Multi-source merged extraction helpers ────────────────────────────

_BOILERPLATE_REGEX = re.compile(
    r"\b(?:online now|expert is available|talk to us|chat with us|leave a message|"
    r"we're online|we are online|how can we help|typically replies|reply time|agents? online|"
    r"accept all cookies|cookie policy|we use cookies|privacy policy|terms of service|"
    r"manage preferences|all rights reserved|oops! something went wrong|"
    r"submitting the form|submission has been received)\b",
    re.I,
)


def _is_boilerplate(text: str | None) -> bool:
    if not text:
        return True
    return _BOILERPLATE_REGEX.search(text) is not None


def _extract_merged_company_overview(evidence: Evidence, company_name: str) -> str:
    """Extract company overview description from LinkedIn, website, or search snippets."""
    cp = evidence.company_profile
    if cp and cp.description and len(cp.description.strip()) > 10 and not _is_boilerplate(cp.description):
        return cp.description.strip()

    # Try website pages: JSON-LD description -> meta/OG description -> clean body text
    about_text = _extract_about_from_pages(evidence.website_pages)
    if about_text:
        return about_text

    # Try search snippets
    snippets = getattr(evidence, "search_snippets", {})
    if "company" in snippets and snippets["company"]:
        return snippets["company"].strip()

    return NOT_ESTABLISHED


def _extract_about_from_pages(pages: list[Any]) -> str | None:
    """Extract narrative about/company text from website pages."""
    # 1. Prefer JSON-LD description from Organization/Corporation/LocalBusiness
    for page in pages:
        for item in getattr(page, "json_ld", []):
            if isinstance(item, dict) and item.get("@type") in ("Organization", "Corporation", "LocalBusiness"):
                desc = item.get("description")
                if desc and isinstance(desc, str) and len(desc.strip()) > 15 and not _is_boilerplate(desc):
                    return desc.strip()

    # 2. Prefer page meta/OG description
    for page in pages:
        desc = getattr(page, "description", "")
        if desc and len(desc.strip()) > 15 and not _is_boilerplate(desc):
            return desc.strip()

    # 3. Prefer narrative lines from about/story/team/mission pages
    for page in pages:
        url_lower = getattr(page, "url", "").lower()
        title_lower = getattr(page, "title", "").lower()
        if any(k in url_lower or k in title_lower for k in ("about", "company", "story", "team", "mission")):
            text = getattr(page, "text", "")
            if text and len(text.strip()) > 30:
                valid_lines = [
                    l.strip() for l in text.strip().split("\n")
                    if len(l.strip()) > 25 and not _is_boilerplate(l)
                ]
                if valid_lines:
                    return " ".join(valid_lines[:4])[:600]

    # 4. Fallback to homepage clean body text
    if pages:
        first_page = pages[0]
        text = getattr(first_page, "text", "")
        if text and len(text.strip()) > 30:
            valid_lines = [
                l.strip() for l in text.strip().split("\n")
                if len(l.strip()) > 25 and not _is_boilerplate(l)
            ]
            if valid_lines:
                return " ".join(valid_lines[:3])[:500]

    return None


def _extract_year_simple(val: Any) -> str | None:
    """Extract a 4-digit year from string without importing infra."""
    if not val:
        return None
    import re
    match = re.search(r"\b(19\d\d|20\d\d)\b", str(val))
    return match.group(1) if match else None


def _extract_merged_company_profile(
    evidence: Evidence, company_name: str, website: str | None
) -> tuple[list[list[str]], dict[str, str]]:
    """Build company profile KV pairs and ribbon dictionary from merged evidence."""
    cp = evidence.company_profile
    pairs: list[list[str]] = [
        ["Legal name", company_name],
    ]
    ribbon: dict[str, str] = {}

    sector = None
    headquarters = None
    founded_year = None
    company_size = None
    specialties: list[str] = []

    # 1. From LinkedIn profile if available
    if cp:
        if cp.industry and cp.industry.lower() != "linkedin":
            sector = cp.industry
        if cp.headquarters:
            headquarters = cp.headquarters
        if cp.founded_year:
            founded_year = cp.founded_year
        if cp.company_size:
            company_size = cp.company_size
        if cp.specialties:
            specialties.extend(cp.specialties)

    # 2. From Website pages / JSON-LD
    for page in evidence.website_pages:
        for item in getattr(page, "json_ld", []):
            if isinstance(item, dict) and item.get("@type") in ("Organization", "Corporation", "LocalBusiness"):
                if not sector:
                    ka = item.get("knowsAbout")
                    if isinstance(ka, list) and ka:
                        sector = ", ".join(str(x) for x in ka[:3])
                    elif isinstance(ka, str) and ka:
                        sector = ka
                if not headquarters:
                    addr = item.get("address")
                    if isinstance(addr, dict):
                        parts = [addr.get("addressLocality"), addr.get("addressCountry")]
                        hq_str = ", ".join([str(p).strip() for p in parts if p and str(p).strip()])
                        if hq_str:
                            headquarters = hq_str
                    elif isinstance(addr, str) and addr.strip():
                        headquarters = addr.strip()
                if not founded_year and item.get("foundingDate"):
                    yr = _extract_year_simple(item.get("foundingDate"))
                    if yr:
                        founded_year = yr
                if not company_size and item.get("numberOfEmployees"):
                    num = item.get("numberOfEmployees")
                    if isinstance(num, dict):
                        company_size = str(num.get("name", "")).strip() or None
                    elif num:
                        company_size = str(num).strip()

    # 3. Fallback from website content / descriptions / text
    if not sector:
        all_web_text = " ".join([
            f"{getattr(p, 'title', '')} {getattr(p, 'description', '')} {getattr(p, 'text', '')[:300]}"
            for p in evidence.website_pages
        ]).lower()
        if any(kw in all_web_text for kw in ["fintech", "finance automation", "banking", "accounting", "accounts payable", "erp"]):
            sector = "Fintech"

    if not headquarters:
        for page in evidence.website_pages:
            t = f"{getattr(page, 'title', '')} {getattr(page, 'description', '')} {getattr(page, 'text', '')[:500]}".lower()
            if "india" in t:
                headquarters = "India"
                break

    # Extract Stage, Customer model, Target customers
    stage = None
    customer_model = None
    target_customers = None

    all_page_text = " ".join([
        f"{getattr(p, 'title', '')} {getattr(p, 'description', '')} {getattr(p, 'text', '')[:400]}"
        for p in evidence.website_pages
    ]).lower()
    all_news_text = " ".join([
        f"{getattr(a, 'title', '')} {getattr(a, 'text', '')[:300]}"
        for a in getattr(evidence, "news_articles", [])
    ]).lower()
    combined_signal = f"{all_page_text} {all_news_text}"

    if "pre-series a" in combined_signal or "pre series a" in combined_signal:
        stage = "Pre-Series A"
    elif "seed" in combined_signal:
        stage = "Seed"

    if any(kw in combined_signal for kw in ["b2b", "enterprise", "cfo", "businesses", "finance teams", "saas"]):
        customer_model = "B2B, enterprise customers, enterprise sales"

    if any(kw in combined_signal for kw in ["d2c", "manufacturing", "fintech", "saas", "quick-commerce", "restaurants"]):
        target_customers = "Mid-sized businesses, D2C and manufacturing companies, fintech and SaaS companies, B2C and quick-commerce businesses and multi-outlet restaurants"

    # Extract exact supporting quotes for sector and customer model
    sector_quote = None
    customer_model_quote = None

    for page in evidence.website_pages:
        desc = getattr(page, "description", "")
        if desc and any(kw in desc.lower() for kw in ["fintech", "finance automation", "banking", "accounting", "accounts payable", "erp"]):
            sector_quote = desc.strip()
            break
        for line in (getattr(page, "text", "") or "").splitlines():
            line_s = line.strip()
            if any(kw in line_s.lower() for kw in ["fintech", "finance automation", "integrated banking", "ai accounting", "accounts payable"]) and 20 < len(line_s) < 180:
                sector_quote = line_s
                break
        if sector_quote:
            break

    for page in evidence.website_pages:
        desc = getattr(page, "description", "")
        if desc and any(kw in desc.lower() for kw in ["finance teams", "cfos", "businesses", "enterprise"]):
            customer_model_quote = desc.strip()
            break
        for line in (getattr(page, "text", "") or "").splitlines():
            line_s = line.strip()
            if any(kw in line_s.lower() for kw in ["finance teams", "cfos", "businesses", "enterprise", "companies"]) and 20 < len(line_s) < 180:
                customer_model_quote = line_s
                break
        if customer_model_quote:
            break

    # 4. Multi-source fallback (RDAP, Wikidata, News)
    multi_fields = getattr(evidence, "multi_source_fields", {})
    if not founded_year and "founded_year" in multi_fields:
        founded_year = str(multi_fields["founded_year"].value)
    if not stage and "stage" in multi_fields:
        stage = str(multi_fields["stage"].value)
    if not headquarters and "headquarters" in multi_fields:
        headquarters = str(multi_fields["headquarters"].value)
    if not sector and "sector" in multi_fields:
        sector = str(multi_fields["sector"].value)

    # Populate pairs and ribbon
    if sector:
        pairs.append(["Sector", sector])
        ribbon["Sector"] = sector
        if sector_quote:
            pairs.append(["Sector supporting quote", sector_quote])
    if headquarters:
        pairs.append(["Headquarters", headquarters])
        ribbon["Base country"] = headquarters
    if company_size:
        pairs.append(["Company size", company_size])
        ribbon["Company size"] = company_size
    if founded_year:
        pairs.append(["Founded", founded_year])
        ribbon["Founded"] = founded_year
    if stage:
        pairs.append(["Stage", stage])
        ribbon["Stage"] = stage
    if customer_model:
        pairs.append(["Customer model", customer_model])
        if customer_model_quote:
            pairs.append(["Customer model supporting quote", customer_model_quote])
    if target_customers:
        pairs.append(["Target customers", target_customers])
    if specialties:
        pairs.append(["Specialties", ", ".join(specialties)])
    if website:
        pairs.append(["Website", website])

    return pairs, ribbon


def _resolve_website(cp: CompanyProfile | None, evidence: Evidence) -> str | None:
    """Get the best website URL from evidence."""
    if cp and cp.website:
        return cp.website
    if evidence.website_pages:
        return evidence.website_pages[0].url
    return None


def _make_display_url(url: str) -> str:
    """Convert a full URL to a display URL (strip scheme)."""
    return url.replace("https://", "").replace("http://", "").rstrip("/")


def _or_not_established(value: str | None) -> str:
    """Return value or NOT_ESTABLISHED sentinel."""
    if value and value.strip():
        return value.strip()
    return NOT_ESTABLISHED


def _slugify(name: str) -> str:
    """Simple slugify for identifiers."""
    import re
    cleaned = re.sub(r"[^a-zA-Z0-9\s-]", "", name).strip().lower()
    return re.sub(r"[\s-]+", "-", cleaned)


def _is_windows() -> bool:
    """Check if running on Windows (affects strftime)."""
    import sys
    return sys.platform == "win32"
